# Site Settings

title: "Ido Hasoy | Portfolio"
header: false
minimal_mistakes_skin: "dark" # Choose a skin if needed
# Disable skip links
include_skip_links: false

description: "Industrial Engineering | Data Analytics | Product Development"
author: "Ido Hasoy"
baseurl: "" # Keep empty if using a custom domain
url: "https://idohasoy.github.io" # Adjust if using a custom domain

# Use Minimal Mistakes Theme
remote_theme: mmistakes/minimal-mistakes

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
nav:
  - title: "Home"
    url: /#home
  - title: "Projects"
    url: /#projects
  - title: "About"
    url: /#about
  - title: "Contact"
    url: /#contact

# Social Links
social:
  linkedin: "https://linkedin.com/in/ido-hasoy"
  github: "https://github.com/IdoHasoy"
  email: "ido.hasoy10@gmail.com"

# Build Settings
exclude:
  - README.md
  - node_modules
  - vendor
