# Site Settings
title: "Ido Hasoy - Portfolio"
description: "Industrial Engineering and Management | Data Analytics | Product Development"
author: "Ido Hasoy"
baseurl: "/IdoHasoy"  # Matches your repo name
url: "https://idohasoy.github.io"

# Use a Professional Theme
remote_theme: pages-themes/cayman@v0.2.0  # Replace with another theme if needed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation Menu
header_pages:
  - index.md
  - projects.md
  - contact.md

# Social Links
social_links:
  linkedin: "https://linkedin.com/in/ido-hasoy"
  github: "https://github.com/IdoHasoy"
  email: "ido.hasoy10@gmail.com"

# Exclude Unnecessary Files
exclude:
  - README.md
