# Site Settings
title: "Ido Hasoy | Portfolio"
header: true
minimal_mistakes_skin: default
description: "Industrial Engineering | Data Analytics | Product Development"
author: "Ido Hasoy"
baseurl: "/IdoHasoy"
url: "https://idohasoy.github.io"

# Use Minimal Mistakes Theme
remote_theme: mmistakes/minimal-mistakes

# Navigation
nav:
  - title: "Home"
    url: /#home
  - title: "Projects"
    url: /#projects
  - title: "Contact"
    url: /#contact

# Social Links
social:
  linkedin: "https://linkedin.com/in/ido-hasoy"
  github: "https://github.com/IdoHasoy"
  email: "ido.hasoy10@gmail.com"

# Build Settings
exclude:
  - README.md
